### ISSUE TITLE
[BUG] Player control are clickable even if the playlist is empty

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#265]
We could prevent PlayerControls button to be clickable if no items in queue and add a some css style.
```css
a {
  cursor: not-allowed;
}
```
