### ISSUE TITLE
Propsole for standard format for exported nuclear playlist

### ISSUE THREAD

**Issue by advaithm** [nukeop/nuclear#878]
Nuclear currently can not export/import playlists and this will change in the future. This issue is proposing a common standard to what nuclear playlists will contain. This will also simplify importing these in nuclear as the format will be known. I am proposing a file that stores the playlist in yaml as there are existing parsers and for the end user it is fairly simple to read and create manually. since the playlist is stored in a file. It should be simple to share on a service should we chose to create one.
```yaml
title: A example playlist
author: Optional field for author of playlist
description: playlist description 
playlist_thumbnail: url_to_the_image
entries:
        - id: 1
          title: The title of the song
          artist: name of aritst
          duration: 5.0.0
          thumbnail: url_to_the_image
        - id: 2
          title: the name of the next entry
          artist: name of aritst
          duration: 5.0.0
          thumbnail: url_to_the_image
```
